### ISSUE TITLE
Set git workflow rules

### ISSUE THREAD

**Issue by henry61024** [program-book-club-for-fun/bookmark-documents#1]

**Comment by Sunnyhsiao** [comment]
建議可以用fork的，這樣久了br比較不會太雜亂

**Comment by henry61024** [comment]
好喔 我們明天可以討論討論

我這邊先推一版上去

**Comment by peterhpchen** [comment]
也可以研究一下[GitHub Flow](https://guides.github.com/introduction/flow/)

較Git Flow單純

**Comment by henry61024** [comment]
GitHub flow 中看起來 master 就算是基底分支嗎

這樣 master 的版本可以確定穩定嗎 (跟 master 解衝突可能會有新的問題產生)

BTW, 大家還有意見可以多討論～～～

**Comment by peterhpchen** [comment]
GitHub Flow的本意是不用建立其他種類的分支，只需要兩種master跟feature就好

如果說是一個很大的feature(1.0到1.1)可以使用long lived feature branch(release branch)

這個分支還會再分其它的feature(功能、除錯...)，大家會對這個分支pr

測試OK後再回到master

這個網頁可以參考: https://gitversion.readthedocs.io/en/latest/git-branching-strategies/githubflow-examples/

**Comment by henry61024** [comment]
github flow 的 feature branch 感覺就有些 dev 分支的感覺

git flow 中的 feature branch 應該是盡量不會再分支出去

**Comment by peterhpchen** [comment]
github flow把分支單純化，不用記這麼多的名詞，對不了解git flow的開發者也比較友善

**Comment by henry61024** [comment]
git flow 切成五個分支真的比較複雜

不過現在提的 flow 只有三個分支ＸＤ

**Comment by Sunnyhsiao** [comment]
覺得我們git公共的的branch應該只需要最多兩個就可以了 master & develop
有太多的反而很雜
我們可以自己另外開branch或是fork以後開branch的時候稍微follow命名規則
eg. feature/add-xxxView (自己另外實作的branch)

**Comment by peterhpchen** [comment]
fork我覺得很好，在專案上的branch會少很多

**Comment by henry61024** [comment]
我覺得我們自己開發的話用branch就可

畢竟也沒多少人，branch 並不會有太多

如果有外面的人要 commit 的話再讓他們 fork

這樣也比較好追蹤進度

**Comment by Sunnyhsiao** [comment]
不過如果我們想要把feature切細的話，br可能就會蠻多的
fork的話功其實不會差很多，就是pull和push的時候寫一下remote name就可以了
我個人是習慣fork
不過如果說真的想要區分我們跟別人所以有fork跟直接開的差別也OK

**Comment by henry61024** [comment]
同時應該不會有很多 br

因為開發時應該要盡量 focus 在一個 issue 上

另外其實我不是很了解很多 br 會衍生什麼問題

主開發幹不是還是 focus 在 dev 上而已嗎

**Comment by henry61024** [comment]
現在對 fork 的感覺最主要的重點是要防止原 repo 內容被亂改

感覺 br 數量反而是其次

**Comment by Sunnyhsiao** [comment]
是不會怎麼樣啦 有點醜而已 XD (還是會怎麼樣只是不太知道)
不過不管fork跟直接開br , 應該都是會focus在同一個issue上 所以沒差
其實就算真的兩個並行也是有的~

**Comment by Sunnyhsiao** [comment]
Y 不然我有個想法
其實還是可以從develop下面開br
但是實作的話我們自己把他fork下來
在各自的local改
這樣也不會改壞
而且有feature的特色

**Comment by henry61024** [comment]
用 fork 的話應該就不需要 feature br 了

因為會經過 PR 才進 dev

**Comment by henry61024** [comment]
話說用 fork 的話通常還會用 dev 嗎？

**Comment by Sunnyhsiao** [comment]
要開feature br送MR的原因，是因為如果直接使用的話，萬一有rebase等操作，這樣會影響到其他人

**Comment by henry61024** [comment]
有點不太懂

只要回到主開發幹，不管是 fork 還是 br 都會影響到其他人吧？

**Comment by Sunnyhsiao** [comment]
如果是fork的話用送MR的方式，rebase時不會影響到他人，這樣也可以把commit整理得好看一點在推上來
如果是直接抓feature br下來，舉例萬一想要rebase，只要推上去，有抓這個br的人都會受到影響

**Comment by henry61024** [comment]
只會抓 dev 不會抓 feature br 下來吧？

盡量不要多人改一條 featuer br

**Comment by Sunnyhsiao** [comment]
可是我們很有可能一個人以上開發共同feature
這個時候就會有共用branch的問題
想像上是會這樣

**Comment by peterhpchen** [comment]
顆粒度夠細，不要讓一個feature需要多人開發，這樣應該不用抓feature br

**Comment by Sunnyhsiao** [comment]
可是有時候難免吧 我所謂的開一個feature br 是例如feature/Add-calendar
這可能前後端都要開發，或是為了開發時程或其他的原因需要分工
自己local端當然還可以再拆細送MR，但是可能就像是feature/Add-calendar-view?
否則每次開發 四個人就有四個以上的feature br了
萬一有相依的資料需要先測試，就會需要等到merge進develop才能測試

**Comment by henry61024** [comment]
git 開新 br 的成本很低，並且開新 br 可以保護其他 br 的內容，所以開分支是被鼓勵的

**Comment by Sunnyhsiao** [comment]
恩恩 開分支是好的
整理一下好了，感覺我上面講得有點亂，可能會看不懂 XD
這些是我目前想到的點

## 如果有共同的feature br 的影響 
1. 共同開發的時候，可以直接驗證feature實作結果
2. 在repo的br管理上面可以一目瞭然，也可以在結束時很清楚直接關閉

如果在上述的情況下，要不影響到共同的feature br
就要自己再開br來處理，然後送MR
如果用fork的話，可以更好管理共同repo上面的branch，
至於自己local端要開幾個br實作，拆多細都沒有關係

## 直接開自己需要實作的feature branch再merge回dev
1. code要等到merge回dev時才能知道有沒有問題
2. 共同repo上面的br很多，如果忘記關的話，容易不好管理

**Comment by peterhpchen** [comment]
* fork的方式專案的br會比較乾淨
* branch的方式在開發上會比較簡單

**Comment by henry61024** [comment]
我認為在 feature br 上共同開發很危險

因為開發的基底就是不穩定的，產出的結果也就很容易錯
